# Generated by Django 5.1.1 on 2024-10-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=123456789, max_length=100),
            preserve_default=False,
        ),
    ]
