# Generated by Django 5.1.1 on 2024-10-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='faculty_number',
            field=models.CharField(),
        ),
    ]
