# Generated by Django 5.1.1 on 2024-10-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_faculty_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.URLField(blank=True),
        ),
    ]
